sudo: required
services:
  - docker

before_install:
  - docker build -t polemarchus/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true polemarchus/react-test npm test

after_success:
  - docker build -t polemarchus/multi-client ./client
  - docker build -t polemarchus/multi-nginx ./nginx
  - docker build -t polemarchus/multi-server ./server
  - docker build -t polemarchus/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to dockerhub
  - docker push polemarchus/multi-client
  - docker push polemarchus/multi-nginx
  - docker push polemarchus/multi-server
  - docker push polemarchus/multi-worker
